cart/urls.py
from django.urls import path

from .views import *


app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add',),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove',),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('onlineshop.urls', namespace='onlineshop')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlineshop/urls.py
from django.urls import path

from onlineshop.views import product_list, product_detail

app_name = 'onlineshop'

urlpatterns = [
    path('',  product_list, name='product_list'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', product_detail, name='product_detail'),

]

cart/models.py
from django.db import models

# Create your models here.

onlineshop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse("onlineshop:product_list_by_category", args=[self.slug])
        

    class Meta:
        ordering = ['-name']
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Product(models.Model):
    category = models.ForeignKey(Category, related_name="products", on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to="products/%Y/%M/%d", blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("onlineshop:product_detail", args=[self.id, self.slug])    

    class Meta:
        ordering = ['-name']
        index_together = (('id', 'slug'),)

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,21)]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST


from .forms import CartAddProductForm
from onlineshop.models import Product

from cart.cart import Cart


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form']=CartAddProductForm(initial={'quantity': item['quantity'], 'override': True})
    return render(request, 'cart/detail.html', {'cart': cart})

onlineshop/views.py
from django.shortcuts import get_object_or_404, render

from cart.forms import CartAddProductForm

from .models import Category, Product

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products  
    }
    return render(request, 'onlineshop/product/list.html', context)        
        
     
def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'onlineshop/product/detail.html', {'product':product, 'cart_product_form': cart_product_form})

cart/templates/cart/detail.html
{% extends 'onlineshop/base.html' %}
{% load static %}



{% block title %}
    Shopping Cart
{% endblock title %}
    


{% block content %}
    <h1>Shopping Cart</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit Price</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
                        <td>
                            <a href=""><img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/default_pr.jpg' %}{% endif %}"></a>
                        </td>
                        <td>{{ product.name }}</td>
                        <td>
                            <form action="{% url 'cart:cart_add' product.id %}" method="POST">
                                {% csrf_token %}
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.override }}
                            <input type="submit" value="Update">
                            </form>
                        </td>
                        <td>
                            <form action="{% url 'cart:cart_remove' product.id %}">
                                <input type="submit" value="Remove">
                            </form>
                        </td>
                        <td class="num">{{ item.price }}$</td>
                        <td class="num">{{ item.total_price }}$</td>

                    </tr>
                {% endwith %}
            {% endfor %}
            <tr class="total">
                <td>Total</td>
                <td colspan=4></td>
                <td class="num">{{ cart.get_total_price }}$</td>
            </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'onlineshop:product_list' %}" class="buttonlight">Continue Shopping</a>
        <a href="#">Check Out</a>
    </p>
{% endblock content %}
    

onlineshop/templates/onlineshop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} My Online Shop {% endblock %} </title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <div id="header">
        <a href="/", class="logo">My Online Shop</a>
    </div>
    <div id="subheader">
        <div class="cart">
            {% with total_items=cart|length  %}
                {% if total_items > 0 %}
                    Your Cart:
                    <a href="{% url 'cart:cart_detail' %}">
                        {{ total_items }} item{{ total_items|pluralize}}
                        {{ cart.get_total_price }}$
                {% else %}
                        Your cart is empty
                {% endif %}
                </a>
            {% endwith %}
        </div>
    </div>
    <div id="content">
        {% block content %}
        
        {% endblock %}
    </div>
    
        
</body>
</html> 

onlineshop/templates/onlineshop/product/detail.html
{% extends 'onlineshop/base.html' %}
{% load static %}


{% block title %}
    {{ product.name }}
{% endblock title %}
    

{% block content%}
    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/default_pr.jpg' %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="price">Price:{{ product.price }}$</p>
        <form action="{% url 'cart:cart_add' product.id %}" method="POST">
            {% csrf_token %}
            {{ cart_product_form }}
            <input type="submit" value="Add to cart">
        </form>
        {{ product.description}}
    </div>
{% endblock %}
    

onlineshop/templates/onlineshop/product/list.html
{% extends 'onlineshop/base.html' %}
{% load static %}

{% block title %}

    {% if category %}

        {{ category.name }}

    {% else %}

        Products

    {% endif %}

{% endblock %}
   

{% block content %}
    <div id="sidebar">
        <h3>Categories</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url 'onlineshop:product_list' %}">All</a>
            </li>
            
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{% endif %} >
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
                
        </ul>
    </div>
    <div>
        <div id="main" class="product-list">
            <h1>{%if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
            
            {% for product in products %}
                <div class="item">
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/default_pr.jpg' %}{% endif %}">
                    </a>
                    <br>
                    ${{ product.price }}
                </div>
            {% endfor %}
                
        </div>
    </div>
{% endblock %}
    